### ISSUE TITLE
Add functionality to run simulations in batches 

### ISSUE THREAD

**Issue by zorian15** [matsengrp/antigen#19]
One of the biggest time sucks of this project is running simulations and looking at tree outputs one-by-one. It would be helpful to 1) have a script to run multiple simulations at a time, preferable on the cluster 2) record some metrics concerning the simulated tree (i.e.  $\pi_{ genealogical}$ and I believe @Haddox had some others in mind) in a file. The idea here would be to create a more efficient and principled way to run multiple simulations and get an idea for how consistent simulations are across phenotype spaces and other hyper parameters. I don't have a detailed implementation plan yet, but will try to work on that over the weekend 😃

**Comment by matsen** [comment]
I'm going to suggest that we try and keep it simple.

1. Let's use a shell script and [GNU parallel](https://github.com/fredhutchio/tfcb_2020/tree/master/lectures/lecture02/06-scripting#gnu-parallel) on one machine (e.g. quoll) for now.
2. Let's just set up a CLI command that runs a sim and writes out metrics, if that's not already done.

**Comment by Haddox** [comment]
Thanks for starting this issue, @zorian15.

Below is our current list of summary statistics that might be nice to know. Some of these may already be in antigen. We should talk about which ones to prioritize.

- Tree has a flu-like shape (genealogical pi)
- Number of epitope vs. non-epitope mutations
- Number of mutations per unit antigenic change
- dN/dS
- Case counts per day
- Time between infections

**Comment by matsen** [comment]
Cool. Those are the "outputs" of a run. What are the input variables that we might like to modify to match those output variables to what we see in data?

**Comment by matsen** [comment]
OK, well, there are two approaches, once we can calculate these quantities:

### 1. try to get intuition by running things by hand

Perhaps this is the thing to try first. Start by just picking some reasonable sounding parameters, then modifying each parameter in turn, say halving and doubling it. Then have a look at how each changes our summary statistics.

### 2. Black box optimization

* [simple option](https://scikit-optimize.github.io/stable/modules/generated/skopt.gp_minimize.html)
* [fancy option](https://github.com/google/vizier)

~~~

By the way, this issue has outgrown its roots: shall we start issues for the summary statistics? Perhaps each gets an issue, or one bundle?

**Comment by zorian15** [comment]
This sounds good to me. Once I have a CLI command + some above summary stats up and running, I'll start with running things by hand again. I've never heard of `vizier` -- but sounds super cool! I'll read more about it and go with whichever seems more appealing. Will also start seperate issues for summary stats.

**Comment by matsen** [comment]
Great. I look forward to talking about summary stats on the various issues, but here are some preliminary notes:


## dN/dS

dN/dS is actually defined to be a ratio of rates, but here I think we are just thinking about a ratio of counts. I think that's good. There's no reason to re-infer the tree at this point.


## Case counts per day

This seems like an interesting vector of values to have, but I'd like to know more about how we are going to use it. Will we want to be comparing it to case counts in real data? Are we going to have an interesting/meaningful comparison there, given that our simulation doesn't have seasonality, etc?

Do we want to compress this vector of values to something simpler?

Or perhaps we just want to spit these things out so we can summarize what the simulation looked like?

## Time between infections

Similar questions here: what underlying data will we be comparing this to?

---

cc @marlinfiggins @huddlej
