### ISSUE TITLE
SequencePhenotype Unit tests

### ISSUE THREAD

**Issue by zorian15** [matsengrp/antigen#5]
I don't think Trevor has any in the original repo, but we should probably get some sort of unit testing implemented for our repo -- I'm familiar with [JUnit](https://junit.org/junit5/docs/current/user-guide/) from my college days but I'm open for anything. If you're game with JUnit @thienktran , I can get this going.

**Comment by thienktran** [comment]
JUnit is great! Thanks for getting that started!
